MODEL:
  PRETRAIN_PATH: '/kaggle/input/weights/r50_ibn_a.pth'
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  NAME: 'resnet50_ibn_a'

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  
DATASETS:
  NAMES: ('UAM')
  ROOT_DIR: '/kaggle/input/uam-base/home/mdb/DL_Lab3/UAM_DATASET/stratified_correct_noC004/Containers'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  #SOFT_MARGIN: False # for model ensemble

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 30
  BASE_LR: 0.00035 #0.00035
  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005
  CLUSTER_MARGIN: 0.3

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 80]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 5
  EVAL_PERIOD: 105

TEST:
  IMS_PER_BATCH: 128
  WEIGHT: "path"
  RE_RANKING: 'yes'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
OUTPUT_DIR: "/kaggle/working/output_BoT/Containers"
